import { param } from "express-validator";
import { validate } from "../validators/authValidators.js";
import { listAssignments, assignStudents, revokeAssignment } from "../controllers/assignmentController.js";
import { Router } from "express";
import { addLesson, addModule, adminCourses, createCourse, deleteCourse, deleteLesson, deleteModule, getCourse, getMyCourse, listCourses, myCourses, setPublished, updateCourse, updateLesson, updateModule, uploadThumbnail } from "../controllers/courseController.js";
import { authorize, protect } from "../middleware/auth.js";
import { uploadThumbnail as thumbnailUpload } from "../middleware/upload.js";
import { courseIdValidator, createCourseValidator, lessonIdValidator, lessonValidator, moduleIdValidator, moduleValidator, publishValidator, updateCourseValidator, updateLessonValidator } from "../validators/courseValidators.js";
const router = Router();
router.get("/", protect, listCourses); router.get("/mine", protect, authorize("instructor", "admin"), myCourses);
router.get("/mine/:id", protect, authorize("instructor", "admin"), courseIdValidator, getMyCourse);
router.get("/admin/all", protect, authorize("admin"), adminCourses);
router.post("/", protect, authorize("instructor", "admin"), createCourseValidator, createCourse);
router.get("/:id", protect, getCourse);
router.patch("/:id", protect, authorize("instructor", "admin"), updateCourseValidator, updateCourse); router.delete("/:id", protect, authorize("instructor", "admin"), courseIdValidator, deleteCourse);
router.patch("/:id/publish", protect, authorize("instructor", "admin"), publishValidator, setPublished); router.post("/:id/thumbnail", protect, authorize("instructor", "admin"), courseIdValidator, thumbnailUpload, uploadThumbnail);
router.post("/:id/modules", protect, authorize("instructor", "admin"), moduleValidator, addModule); router.patch("/:id/modules/:moduleId", protect, authorize("instructor", "admin"), moduleValidator, updateModule); router.delete("/:id/modules/:moduleId", protect, authorize("instructor", "admin"), moduleIdValidator, deleteModule);
router.post("/:id/modules/:moduleId/lessons", protect, authorize("instructor", "admin"), lessonValidator, addLesson); router.patch("/:id/lessons/:lessonId", protect, authorize("instructor", "admin"), updateLessonValidator, updateLesson); router.delete("/:id/lessons/:lessonId", protect, authorize("instructor", "admin"), lessonIdValidator, deleteLesson);
router.get("/:id/assignments", protect, authorize("instructor", "admin"), courseIdValidator, listAssignments);
router.post("/:id/assignments", protect, authorize("instructor", "admin"), courseIdValidator, assignStudents);
router.delete("/:id/assignments/:studentId", protect, authorize("instructor", "admin"), courseIdValidator, param("studentId").isMongoId(), validate, revokeAssignment);
export default router;
