import { Router } from "express";
import { param } from "express-validator";
import rateLimit from "express-rate-limit";
import { protect, authorize } from "../middleware/auth.js";
import { validate } from "../validators/authValidators.js";
import { askQuestion, listQuestions, listTasks, practicalRecords, replyQuestion, resolveQuestion, savePracticalRecord, saveTask } from "../controllers/learningSupportController.js";
const r = Router(), ids = (...names) => [...names.map((n) => param(n).isMongoId()), validate];
const writes = rateLimit({ windowMs: 60 * 60 * 1000, max: 120, keyGenerator: (req) => String(req.user._id), standardHeaders: true, legacyHeaders: false, message: { message: "Too many support changes. Try again later." } });
const questions = rateLimit({ windowMs: 60 * 60 * 1000, max: 10, keyGenerator: (req) => String(req.user._id), standardHeaders: true, legacyHeaders: false, message: { message: "Too many question requests. Try again later." } });
r.get("/courses/:courseId/practicals", protect, ...ids("courseId"), listTasks);
r.post("/courses/:courseId/practicals", protect, authorize("instructor", "admin"), writes, ...ids("courseId"), saveTask);
r.put("/courses/:courseId/practicals/:id", protect, authorize("instructor", "admin"), writes, ...ids("courseId", "id"), saveTask);
r.post("/practicals/:id/record", protect, authorize("student"), writes, ...ids("id"), savePracticalRecord);
r.get("/courses/:courseId/practical-records", protect, authorize("instructor", "admin"), ...ids("courseId"), practicalRecords);
r.get("/courses/:courseId/questions", protect, ...ids("courseId"), listQuestions);
r.post("/courses/:courseId/questions", protect, authorize("student"), questions, ...ids("courseId"), askQuestion);
r.post("/course-questions/:id/replies", protect, authorize("instructor", "admin"), writes, ...ids("id"), replyQuestion);
r.put("/course-questions/:id/status", protect, authorize("student"), writes, ...ids("id"), resolveQuestion);
export default r;
