import { Router } from "express";
import { param } from "express-validator";
import { limitConcurrentChunks } from "../middleware/requestLimits.js";
import { protect, authorize } from "../middleware/auth.js";
import { validate } from "../validators/authValidators.js";
import { createUpload, uploadStatus, uploadChunk, completeUpload, removeUpload, streamVideo, verifyChunk } from "../controllers/videoController.js";
import { createDirectUpload, directUploadTicket, completeDirectUpload, playbackTicket } from "../controllers/directVideoController.js";
const router = Router();
const id = (name) => [param(name).isMongoId(), validate];
router.get("/lessons/:lessonId/playback", protect, ...id("lessonId"), playbackTicket);
router.post("/lessons/:lessonId/direct-uploads", protect, authorize("instructor", "admin"), ...id("lessonId"), createDirectUpload);
router.post("/direct-uploads/:id/url", protect, authorize("instructor", "admin"), ...id("id"), directUploadTicket);
router.post("/direct-uploads/:id/complete", protect, authorize("instructor", "admin"), ...id("id"), completeDirectUpload);
router.get("/lessons/:lessonId/video", protect, ...id("lessonId"), streamVideo);
router.post("/lessons/:lessonId/uploads", protect, authorize("instructor", "admin"), ...id("lessonId"), createUpload);
router.get("/uploads/:id", protect, authorize("instructor", "admin"), ...id("id"), uploadStatus);
router.put("/uploads/:id/chunks/:index", protect, authorize("instructor", "admin"), ...id("id"), limitConcurrentChunks, uploadChunk);
router.post("/uploads/:id/chunks/:index/verify", protect, authorize("instructor", "admin"), ...id("id"), verifyChunk);
router.post("/uploads/:id/complete", protect, authorize("instructor", "admin"), ...id("id"), completeUpload);
router.delete("/uploads/:id", protect, authorize("instructor", "admin"), ...id("id"), removeUpload);
export default router;
