import mongoose from "mongoose";
const oid = (ref) => ({ type: mongoose.Schema.Types.ObjectId, ref, required: true });
const config = new mongoose.Schema({ course: oid("Course"), measurementEnabled: { type: Boolean, default: false }, interestEnabled: { type: Boolean, default: false }, reviewedPolicyUrl: { type: String, default: "" }, reviewedAt: Date, version: { type: Number, default: 1 } }, { timestamps: true });
config.index({ course: 1 }, { unique: true });
export const AcquisitionConfig = mongoose.model("AcquisitionConfig", config);
const source = new mongoose.Schema({ course: oid("Course"), slot: { type: Number, min: 0, max: 19, required: true }, code: { type: String, required: true }, requestToken: { type: String, required: true, select: false }, channel: { type: String, enum: ["website", "social", "search", "referral", "email", "print", "other"], required: true }, label: { type: String, maxlength: 40, required: true }, active: { type: Boolean, default: true }, version: { type: Number, default: 1 } }, { timestamps: true });
source.index({ course: 1, slot: 1 }, { unique: true });
source.index({ course: 1, code: 1 }, { unique: true });
source.index({ course: 1, requestToken: 1 }, { unique: true });
export const SourceLink = mongoose.model("SourceLink", source);
const visit = new mongoose.Schema({ course: oid("Course"), source: { type: mongoose.Schema.Types.ObjectId, ref: "SourceLink", default: null }, slot: { type: Number, min: 0, max: 4999, required: true }, requestToken: { type: String, required: true, select: false }, expiresAt: { type: Date, required: true } }, { timestamps: true });
visit.index({ course: 1, slot: 1 }, { unique: true });
visit.index({ course: 1, requestToken: 1 }, { unique: true });
visit.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });
export const AcquisitionVisit = mongoose.model("AcquisitionVisit", visit);
const choice = new mongoose.Schema({ course: oid("Course"), student: oid("User"), source: oid("SourceLink"), expiresAt: { type: Date, required: true } }, { timestamps: true });
choice.index({ course: 1, student: 1 }, { unique: true });
choice.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });
export const AcquisitionChoice = mongoose.model("AcquisitionChoice", choice);
const interest = new mongoose.Schema({ course: oid("Course"), slot: { type: Number, min: 0, max: 499, required: true }, email: { type: String, required: true, maxlength: 254 }, purpose: { type: String, enum: ["interest", "demo"], required: true }, marketingConsent: { type: Boolean, default: false }, marketingConsentAt: Date, requestToken: { type: String, required: true, select: false }, policyUrl: String, status: { type: String, enum: ["pending", "contacted", "closed"], default: "pending" }, version: { type: Number, default: 1 }, expiresAt: { type: Date, required: true } }, { timestamps: true });
interest.index({ course: 1, slot: 1 }, { unique: true });
interest.index({ course: 1, requestToken: 1 }, { unique: true });
interest.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });
export const InterestRequest = mongoose.model("InterestRequest", interest);
export const acquisitionModels = [AcquisitionConfig, SourceLink, AcquisitionVisit, AcquisitionChoice, InterestRequest];
